### ISSUE TITLE
SQL Injection possible 

### ISSUE THREAD

**Issue by sidcool1234** [CeeqlGroup/ceeql#10]
While sending an HTTP request for a query:

`select distinct {{column_name}} from {{table_name}} order by id desc;`

If I send the HTTP query like:

`/path/identifier?column_name=column&table_name=table;insert%20into%20demo%20values(11)--;`

The resulting query is:

`select distinct(column) from table; insert into demo values(11);-- order by id;`

Why is this not being escaped?

**Comment by mrcsparker** [comment]
You should be using the `:param` format and not the `{{}}` format to escape values

**Comment by sidcool1234** [comment]
> You should be using the `:param` format and not the `{{}}` format to escape values

Thanks Chris.  We figured after going through the documentation.  This library has helped us immensely.
